SWI-3665 Update SDK Based on Recent Spec Changes
Bandwidth/java-sdk pull request #102
Opened 2023-10-03 14:41 UTC by DX-Bandwidth

Auto-generated by Update SDK Workflow

2023-10-03 14:48 UTC, brianluisgomez approved these changes

2023-10-03 15:34 UTC, ajrice6713 approved these changes

2023-10-03 17:25 UTC, ajrice6713 commented
Putting this in draft - we cant add tests till GET /calls goes GA on 8/9

2023-11-01 13:19 UTC, ckoegel approved these changes

2023-11-01 13:54 UTC, ajrice6713 requested changes

2023-11-01 13:54 UTC, ajrice6713 commented on src/test/java/com/bandwidth/sdk/api/CallsApiTest.java
> +    private static int TEST_SLEEP = 6;
I think we want to set this to 40 to mimic voice api teams alarm, right @ckoegel ?

2023-11-01 13:54 UTC, ajrice6713 commented on src/test/java/com/bandwidth/sdk/api/ConferencesApiTest.java
> +    private static int TEST_SLEEP = 6;
Same here, set the sleep to 40 and dont retry.

2023-11-01 13:57 UTC, ckoegel commented on src/test/java/com/bandwidth/sdk/api/ConferencesApiTest.java
> +    private static int TEST_SLEEP = 6;
Here I believe this is used for waiting for the recording to finish, so we want to sleep less and retry to poll manteca

2023-11-01 13:59 UTC, ckoegel commented on src/test/java/com/bandwidth/sdk/api/CallsApiTest.java
> +    private static int TEST_SLEEP = 6;
this one should also be fine cause we use it in multiple spots, we should just update the sleep for get call state to be 40s

2023-11-01 13:59 UTC, ckoegel commented on src/test/java/com/bandwidth/sdk/api/CallsApiTest.java
> +        TimeUnit.SECONDS.sleep(TEST_SLEEP);
```suggestion
        TimeUnit.SECONDS.sleep(40);
```

2023-11-01 14:30 UTC, ajrice6713 approved these changes

2023-11-01 15:12 UTC, merged