Tag & SipUri BXML
Bandwidth/java-sdk pull request #13
Opened 2020-12-07 19:55 UTC by jchavez443

Leave a comment!

2020-12-07 20:12 UTC, jmulford-bw requested changes
Do you have to do anything to make the SipUri nestable in the transfer verb?

2020-12-07 20:19 UTC, jchavez443 commented
We could but then it would get messy with Lombok.  Besides that not how the phoneNumber bxml verb was built either.

2020-12-07 20:26 UTC, hamermike commented on src/main/java/com/bandwidth/voice/bxml/verbs/Transfer.java
> +     * A collection of SipUrs to transfer the call to. The first to answer will be transferred.
SipUr**i**s

2020-12-07 20:38 UTC, hamermike approved these changes

2020-12-07 22:06 UTC, hamermike approved these changes

2020-12-08 13:11 UTC, jmulford-bw approved these changes

2020-12-08 14:18 UTC, merged