DX-2052 phone number lookup sdk support
Bandwidth/java-sdk pull request #33
Opened 2021-06-23 11:59 UTC by jmulford-bw

2021-06-23 13:30 UTC, hamermike requested changes

2021-06-23 13:30 UTC, hamermike commented on src/main/java/com/bandwidth/BandwidthClient.java
> +
Using this method instead of `getTimeout()` is a breaking change for anyone who may be using `getTimeout()`.

2021-06-23 13:30 UTC, hamermike commented on src/main/java/com/bandwidth/BandwidthClient.java
> +        twoFactorAuthClient = new TwoFactorAuthClient(this); //danger
What is _danger_? 😄

2021-06-23 13:30 UTC, hamermike commented on src/main/java/com/bandwidth/BandwidthClient.java
> -        builder.timeout = getTimeout();
Same as above related to nuking `getTimeout()`.

2021-06-23 14:00 UTC, ajrice6713 submitted a review, later dismissed

2021-06-23 14:04 UTC, jmulford-bw commented on src/main/java/com/bandwidth/BandwidthClient.java
> +        twoFactorAuthClient = new TwoFactorAuthClient(this); //danger
Ha. Personal reminder. Removed

2021-06-23 14:04 UTC, jmulford-bw commented on src/main/java/com/bandwidth/BandwidthClient.java
> +
I kept this method and also re-added the previous `getTimeout()` method

2021-06-23 14:04 UTC, jmulford-bw commented on src/main/java/com/bandwidth/BandwidthClient.java
> -        builder.timeout = getTimeout();
Good catch, reverted

2021-06-23 14:25 UTC, hamermike approved these changes

2021-06-23 14:38 UTC, ajrice6713 approved these changes

2021-06-23 14:38 UTC, merged

2022-09-16 10:23 UTC, JuicyJ22 approved these changes