It's Happening
Bandwidth/java-sdk pull request #46
Opened 2021-09-27 17:45 UTC by abaldwin-Bandwidth

2021-09-29 13:30 UTC, hamermike requested changes
@adamrbaldwin-bw could you please add some checks for the response status codes in these?

2021-09-29 13:32 UTC, ajrice6713 requested changes

2021-09-29 13:32 UTC, ajrice6713 commented on src/test/java/com/bandwidth/MfaApiTests.java
> +        assertFalse("MessageID is empty", response.getMessageId().isEmpty());
I think we want to check for status codes in the response body as well as the length of the message ID string to ensure it isnt changing (that has broken customers previously)

2021-09-29 13:32 UTC, ajrice6713 commented on src/test/java/com/bandwidth/MfaApiTests.java
> +        assertFalse("CallID is empty", response.getCallId().isEmpty());
We want to assert status code and len of CallID here as well

2021-09-29 13:32 UTC, ajrice6713 commented on src/test/java/com/bandwidth/WebRtcApiTests.java
> +        // expected response is an empty 204
I think we can assert the status codes of the deletes here

2021-10-04 19:27 UTC, ajrice6713 approved these changes

2021-10-04 19:41 UTC, hamermike approved these changes

2021-10-04 19:45 UTC, merged