DX-2231 Updated to Include Matrix Testing
Bandwidth/java-sdk pull request #47
Opened 2021-09-29 18:34 UTC by ckoegel

2021-09-29 19:57 UTC, hamermike commented
@ckoegel what if I told you there were different Java distributions?
https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Testing-against-different-Java-distributions
👀

2021-09-29 19:59 UTC, hamermike commented on .github/workflows/test.yml
>          distribution: 'adopt'
`adopt` is being phased out and replaced with `temurin`. I know you didn't mess with this but we should update.

2021-09-29 20:04 UTC, ckoegel commented on .github/workflows/test.yml
>          distribution: 'adopt'
should I make a matrix for the distributions?

2021-09-29 20:04 UTC, ckoegel commented on .github/workflows/test.yml
>          distribution: 'adopt'
akin to `distribution: [ 'zulu', 'temurin' ]` with `distribution: ${{ matrix.distribution }}`?

2021-09-30 14:39 UTC, ajrice6713 submitted a review, later dismissed

2021-09-30 16:37 UTC, hamermike requested changes

2021-09-30 16:37 UTC, hamermike commented on .github/workflows/test.yml
> +        distribution: [ 'zulu', 'temurin' ]
```suggestion
        distribution: ['zulu', 'temurin']
```

2021-09-30 16:37 UTC, hamermike commented on README.md
> +| Ubuntu 20.04 | 8, 11 |
```suggestion
| **OS** | **Java** | **Distribution** |
|:---:|:---:|:---:|
| Windows 2016 | 8, 11 | Zulu OpenJDK, Eclipse Temurin |
| Windows 2019 | 8, 11 | Zulu OpenJDK, Eclipse Temurin |
| Ubuntu 18.04 | 8, 11 | Zulu OpenJDK, Eclipse Temurin |
| Ubuntu 20.04 | 8, 11 | Zulu OpenJDK, Eclipse Temurin |
```

2021-09-30 16:37 UTC, hamermike commented on src/test/java/com/bandwidth/ApiTest.java
> +        // assertEquals("Call ID not equal", callId, callStateResponse.getResult().getCallId());
I assume this is temporary and will get swapped with @adamrbaldwin-bw's tests?

2021-09-30 17:59 UTC, ckoegel commented on src/test/java/com/bandwidth/ApiTest.java
> +        // assertEquals("Call ID not equal", callId, callStateResponse.getResult().getCallId());
yes it is

2021-09-30 18:30 UTC, hamermike approved these changes

2021-09-30 19:03 UTC, ajrice6713 approved these changes

2021-09-30 19:40 UTC, abaldwin-Bandwidth approved these changes

2021-09-30 19:47 UTC, merged