DX-2226 Updated XML Declaration
Bandwidth/java-sdk pull request #48
Opened 2021-09-30 15:42 UTC by ckoegel

2021-09-30 17:25 UTC, hamermike submitted a review, later dismissed

2021-09-30 18:29 UTC, hamermike approved these changes

2021-09-30 18:51 UTC, ajrice6713 requested changes

2021-09-30 18:51 UTC, ajrice6713 commented on src/main/java/com/bandwidth/voice/bxml/verbs/Response.java
>              // omits <?xml version="1.0" encoding="UTF-8"?>
Can we remove the comment?

2021-10-01 14:52 UTC, hamermike approved these changes

2021-10-01 16:41 UTC, ajrice6713 approved these changes

2021-10-01 17:45 UTC, merged