DX-2700
Bandwidth/java-sdk pull request #72
Opened 2022-08-01 19:34 UTC by brianluisgomez

2022-08-03 17:18 UTC, ajrice6713 approved these changes

2022-08-04 14:39 UTC, bpateldx requested changes

2022-08-04 14:39 UTC, bpateldx commented on .settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=1.5
This IDE specific file should be ignored from VCS

2022-08-04 14:39 UTC, bpateldx commented on src/test/java/com/bandwidth/BxmlTest.java
> +            .build();
Test for all elements/attributes including `tracks`

2022-08-04 21:27 UTC, bpateldx approved these changes

2022-08-05 13:25 UTC, ajrice6713 approved these changes

2022-08-29 19:49 UTC, merged