DX-2890 Messaging Integration Tests
Bandwidth/java-sdk pull request #75
Opened 2022-10-19 15:34 UTC by brianluisgomez

Added messaging integration tests using hamcrest and added a utilities folder with environment params for use in all integration tests

2022-10-21 18:04 UTC, ajrice6713 requested changes

2022-10-21 18:04 UTC, ajrice6713 commented on src/test/java/org/openapitools/client/utils/TestingEnvironmentVariables.java
> +    private TestingEnvironmentVariables(){}
Whats the purpose of having this here?

2022-10-31 12:37 UTC, brianluisgomez commented on .settings/org.eclipse.jdt.core.prefs
> +enableParallelJavaIndexSearch=true
Looking online it looks like it does usually get ignored so I changed that.

2022-10-31 12:40 UTC, brianluisgomez commented on pom.xml
> +        <dependency>
It does get overwritten so I added it to .openapigeneratorignore

2022-11-07 15:40 UTC, ajrice6713 approved these changes

2022-11-07 15:57 UTC, ckoegel approved these changes

2022-11-07 16:01 UTC, merged