DX-2889 Add Media API Integration Tests
Bandwidth/java-sdk pull request #81
Opened 2023-02-03 19:01 UTC by ajrice6713

2023-02-07 12:42 UTC, brianluisgomez submitted a review, later dismissed

2023-02-10 21:35 UTC, matthewkmartin requested changes

2023-02-10 21:35 UTC, matthewkmartin commented on src/test/java/org/openapitools/client/api/MediaApiTest.java
> +    private String content_type = "image/jpeg";
```suggestion
    private String contentType = "image/jpeg";
```

2023-02-10 21:35 UTC, matthewkmartin commented on src/test/java/org/openapitools/client/api/MediaApiTest.java
> +    private String cache_control = "no-cache";
```suggestion
    private String cacheControl = "no-cache";
```

2023-02-10 21:35 UTC, matthewkmartin commented on src/test/java/org/openapitools/client/api/MediaApiTest.java
> +                this.content_type,
```suggestion
                this.contentType,
```

2023-02-10 21:35 UTC, matthewkmartin commented on src/test/java/org/openapitools/client/api/MediaApiTest.java
> +                this.cache_control);
```suggestion
                this.cacheControl);
```

2023-02-14 13:25 UTC, matthewkmartin approved these changes

2023-02-15 16:40 UTC, ckoegel commented on src/test/java/org/openapitools/client/api/MediaApiTest.java
> +        System.out.println(this.mediaId);
is there a reason for all of these printlns?

2023-02-15 20:06 UTC, ajrice6713 commented on src/test/java/org/openapitools/client/api/MediaApiTest.java
> +        System.out.println(this.mediaId);
No - removed

2023-02-17 13:05 UTC, brianluisgomez commented on pom.xml
> +</project>
```suggestion
</project>

```

2023-02-17 15:34 UTC, ckoegel submitted a review, later dismissed

2023-02-20 14:43 UTC, brianluisgomez approved these changes

2023-02-20 14:46 UTC, brianluisgomez approved these changes

2023-02-20 15:00 UTC, ckoegel approved these changes

2023-02-20 15:01 UTC, merged