SWI-3348 Add `update-sdk` workflow
Bandwidth/java-sdk pull request #96
Opened 2023-08-28 15:24 UTC by ajrice6713

2023-08-28 20:53 UTC, juliajanu submitted a review, later dismissed

2023-08-28 20:54 UTC, hamermike requested changes

2023-08-28 20:54 UTC, hamermike commented on .github/workflows/update-sdk.yml
> +    runs-on: ${{ fromJSON(vars.SWI_GLORG_UBUNTU_2204) }}
```suggestion
    runs-on: ${{ fromJSON(vars.SWI_GLORG_UBUNTU_2204) }}
```
Shared runners don't work on public repos.

2023-08-28 20:54 UTC, hamermike commented on .github/workflows/update-sdk.yml
> +            workloads/prod/software_infra::secrets:SDLC-Enforcer-Prod:JIRA_USERNAME@9::JIRA_USERNAME
Vault requires hosted runners. Can't use Vault.

2023-08-28 20:54 UTC, ckoegel approved these changes

2023-08-29 13:45 UTC, hamermike commented on .github/workflows/update-sdk.yml
> +    runs-on: ${{ fromJSON(vars.SWI_GLORG_UBUNTU_2204) }}
@ajrice6713 runs are going to still blow up on you.

2023-08-29 19:32 UTC, juliajanu approved these changes

2023-08-31 15:25 UTC, hamermike approved these changes

2023-08-31 19:05 UTC, merged